# line extraction parameters.
m_least_thresh: 0.045 # 3 sigma rule.
m_min_length: 0.1
m_predict_distance: 0.035
m_seed_pts_num: 7
m_min_line_points_num: 12
config_sincos_flag: true
m_missing_pts_tolerance: 1
m_gap_distance_tolerance: 0.3

# laser scanner parameters.
m_laser_points_num: 1079
m_laser_angle_min: -2.35183119774
m_laser_angle_max: 2.35183119774
m_laser_angle_incre: 0.00436332309619
m_laser_range_min: 0.0
m_laser_range_max: 60.0


# matching parameters.
plane_pairing_thresh: 1.0
plane_pairing_intersection_ratio: 0.25

hist_bin_width: 2.0
hist_bin_min: -90.0
hist_bin_max: 90.0
hist_search_window: 36
hist_absorb_bin_num: 2
plane_similar_ratio: 4.0 # deg.

dist_noise_bound: 0.04
angular_noise_bound: 2.0 # deg.

eigen_threshold1: 0.5
eigen_threshold2: 0.5