# line extraction parameters.
m_least_thresh: 0.05 # 3 sigma rule.
m_min_length: 0.35
m_predict_distance: 0.045
m_seed_pts_num: 10
m_min_line_points_num: 15
config_sincos_flag: false
m_missing_pts_tolerance: 1
m_gap_distance_tolerance: 0.2

# laser scanner parameters.
m_laser_points_num: 1800
m_laser_angle_min: -3.14159274101
m_laser_angle_max: 3.14159274101
m_laser_angle_incre: 0.00349065847695
m_laser_range_min: 0.0
m_laser_range_max: 30.0


# matching parameters.
plane_pairing_thresh: 1.0
plane_pairing_intersection_ratio: 0.5

hist_bin_width: 2.0
hist_bin_min: -90.0
hist_bin_max: 90.0
hist_search_window: 70
hist_absorb_bin_num: 3
plane_similar_ratio: 5.0 # deg.

dist_noise_bound: 0.04
angular_noise_bound: 3.0 # deg.

eigen_threshold1: 0.5
eigen_threshold2: 0.5